Repository dhairyagothi/100_days_100_web_project, pull requests merged in 2024-06, with the labels that each got.

#8 Added 24th day project ChatBot that accepts text and files
  README.md
  public/AI ChatBot/chatbot.html
  public/AI ChatBot/style.css
Labels: documentation, enhancement, VSoC'24, HARD

#21 Added WORDLE Game
  public/WORDLE/assets/css/style.css
  public/WORDLE/assets/js/script.js
  public/WORDLE/assets/js/words.js
  public/WORDLE/img/information.png
  public/WORDLE/img/rules.png
  public/WORDLE/img/statistics.png
  public/WORDLE/img/wordle.jpg
  public/WORDLE/img/wordleimage.png
  public/WORDLE/index.html
  public/index.html
Labels: documentation, enhancement, VSoC'24, MEDIUM

#24 Add Simple Snake Game Implementation with Documentation
  public/index.html
  public/snake_game/index.css
  public/snake_game/index.html
  public/snake_game/index.js
Labels: VSoC'24, IN-PROGRESS

#30 Password Manager is been uploaded
  public/index.html
  public/password manager/copy.svg
  public/password manager/index.html
  public/password manager/script.js
  public/password manager/style.css
Labels: documentation, enhancement, VSoC'24, HARD

#38 Project DropDown Navigation Bar is Completed
  public/dropdown_navbar/dropdown.css
  public/dropdown_navbar/dropdown.html
  public/dropdown_navbar/img/pic.jpg
  public/dropdown_navbar/index.html
  public/dropdown_navbar/input.css
  public/dropdown_navbar/readme.md
Labels: enhancement, good first issue, VSoC'24, HARD, IN-PROGRESS

#47 Flappy Bird
  public/Flappy-bird-main/bottompipe.png
  public/Flappy-bird-main/flappybird.png
  public/Flappy-bird-main/flappybirdbg.png
  public/Flappy-bird-main/index.html
  public/Flappy-bird-main/toppipe.png
  public/index.html
Labels: enhancement, VSoC'24, MEDIUM

#60 weather forcasting is done
  public/email validator/background.jpeg
  public/email validator/email.svg
  public/email validator/index.html
  public/email validator/loading.svg
  public/email validator/script.js
  public/email validator/style.css
  public/index.html
Labels: enhancement, VSoC'24, MEDIUM

#54 Add Jarvis Voice Assistant issue #48
  public/Jarvis-AI-main/LICENSE
  public/Jarvis-AI-main/app.js
  public/Jarvis-AI-main/avatar.png
  public/Jarvis-AI-main/giphy.gif
  public/Jarvis-AI-main/index.html
  public/Jarvis-AI-main/style.css
  public/index.html
Labels: IN-PROGRESS

#73 Simple and Elegant Calculator Using Vanilla JavaScript
  public/Vanilla-JavaScript-Calculator-master/index.html
  public/Vanilla-JavaScript-Calculator-master/script.js
  public/Vanilla-JavaScript-Calculator-master/styles.css
  public/index.html
Labels: enhancement, VSoC'24, MEDIUM

#76 Feature/notes app
  node_modules/.package-lock.json
  node_modules/body-parser/HISTORY.md
  node_modules/body-parser/README.md
  node_modules/body-parser/lib/types/json.js
  node_modules/body-parser/package.json
  node_modules/braces/LICENSE
  node_modules/braces/README.md
  node_modules/braces/index.js
  node_modules/braces/lib/compile.js
  node_modules/braces/lib/constants.js
  node_modules/braces/lib/expand.js
  node_modules/braces/lib/parse.js
  node_modules/braces/lib/stringify.js
  node_modules/braces/lib/utils.js
  node_modules/braces/package.json
  node_modules/cookie/HISTORY.md
  node_modules/cookie/README.md
  node_modules/cookie/index.js
  node_modules/cookie/package.json
  node_modules/express/History.md
  node_modules/express/Readme.md
  node_modules/express/lib/response.js
  node_modules/express/lib/router/index.js
  node_modules/express/lib/router/route.js
  node_modules/express/lib/utils.js
  node_modules/express/package.json
  node_modules/fill-range/index.js
  node_modules/fill-range/package.json
  node_modules/hasown/CHANGELOG.md
  node_modules/hasown/index.d.ts
  node_modules/hasown/package.json
  node_modules/hasown/tsconfig.json
  node_modules/raw-body/HISTORY.md
  node_modules/raw-body/README.md
  node_modules/raw-body/index.js
  node_modules/raw-body/package.json
  node_modules/set-function-length/CHANGELOG.md
  node_modules/set-function-length/env.d.ts
  node_modules/set-function-length/env.js
  node_modules/set-function-length/index.d.ts
  node_modules/set-function-length/index.js
  node_modules/set-function-length/package.json
  node_modules/set-function-length/tsconfig.json
  node_modules/side-channel/CHANGELOG.md
  node_modules/side-channel/index.js
  node_modules/side-channel/package.json
  node_modules/side-channel/test/index.js
  public/index.html
  public/notes-app/index.html
  public/notes-app/script.js
  public/notes-app/style.css
Labels: enhancement, VSoC'24, HARD

#78 Added github profile finder project
  public/github_profile_finder/.gitignore
  public/github_profile_finder/README.md
  public/github_profile_finder/package-lock.json
  public/github_profile_finder/package.json
  public/github_profile_finder/public/favicon.ico
  public/github_profile_finder/public/index.html
  public/github_profile_finder/public/logo192.png
  public/github_profile_finder/public/logo512.png
  public/github_profile_finder/public/manifest.json
  public/github_profile_finder/public/robots.txt
  public/github_profile_finder/src/App.css
  public/github_profile_finder/src/App.js
  public/github_profile_finder/src/App.test.js
  public/github_profile_finder/src/components/Finder.jsx
  public/github_profile_finder/src/components/Profile.jsx
  public/github_profile_finder/src/components/Repo.jsx
  public/github_profile_finder/src/components/RepoDetails.jsx
  public/github_profile_finder/src/index.css
  public/github_profile_finder/src/index.js
  public/github_profile_finder/src/logo.svg
  public/github_profile_finder/src/reportWebVitals.js
  public/github_profile_finder/src/setupTests.js
  public/github_profile_finder/tailwind.config.js
  public/index.html
Labels: enhancement, VSoC'24, HARD

#84 Analog Clock
  public/AnalogClock/clock.png
  public/AnalogClock/index.css
  public/AnalogClock/index.html
  public/AnalogClock/index.js
  public/index.html
Labels: enhancement, VSoC'24, MEDIUM

#88 closes #3 aligned the preloader
  public/home.css
Labels: enhancement, VSoC'24, EASY

#91 Amazon Clone is updated
  public/Amazon_Clone/index.html
  public/Amazon_Clone/style.css
  public/index.html
Labels: documentation, enhancement, VSoC'24, MEDIUM

#94 Project Password Generator Completed
  public/Password_Generator/index.html
  public/Password_Generator/lock.png
  public/Password_Generator/script.js
  public/Password_Generator/style.css
  public/index.html
Labels: enhancement, VSoC'24, MEDIUM

#99 new clock faces, time zone and Set Alarm feature is added
  public/digital_clock/digitalclock.css
  public/digital_clock/digitalclock.html
  public/digital_clock/digitalclock.js
  public/discord/__pycache__/discord.cpython-312.pyc
Labels: enhancement, VSoC'24, MEDIUM

#118 Project Budget Tracker Completed
  public/Budget Tracker/budget.jpg
  public/Budget Tracker/index.html
  public/Budget Tracker/script.js
  public/Budget Tracker/style.css
  public/index.html
Labels: enhancement, VSoC'24, MEDIUM

#119 Enhancing To-Do List Functionality with PDF Export and Document Manag…
  public/TO_DO_LIST/todolist.css
  public/TO_DO_LIST/todolist.html
  public/TO_DO_LIST/todolist.js
Labels: documentation, VSoC'24, MEDIUM

#127 Ping Ball Game
  public/index.html
  public/ping/index.html
  public/ping/script.js
  public/ping/style.css
Labels: enhancement, VSoC'24, MEDIUM

#132 TextToVoiceConverter
  public/TextToVoiceConverter/abc.jpeg
  public/TextToVoiceConverter/index.html
  public/TextToVoiceConverter/script.js
  public/TextToVoiceConverter/styles.css
  public/index.html
Labels: documentation, enhancement, VSoC'24, MEDIUM

#134 project: add url shortener
  public/index.html
  public/url_shortener/.gitignore
  public/url_shortener/README.md
  public/url_shortener/index.html
  public/url_shortener/input.css
  public/url_shortener/package.json
  public/url_shortener/server.ts
  public/url_shortener/tailwind.config.js
  public/url_shortener/tsconfig.json
  public/url_shortener/yarn.lock
Labels: documentation, enhancement, VSoC'24, MEDIUM

#129 Implement Netflix Clone
  public/Netflix_Cloning/Index.html
  public/Netflix_Cloning/Video/video1.m4v
  public/Netflix_Cloning/favicon.png
  public/Netflix_Cloning/img/bg.jpg
  public/Netflix_Cloning/img/image2.png
  public/Netflix_Cloning/img/logo.svg
  public/Netflix_Cloning/styles.css
  public/index.html
Labels: invalid, Changes needed, IN-PROGRESS

#138 Recipe Genie app
  public/Recipe Genie/.eslintrc.cjs
  public/Recipe Genie/.gitignore
  public/Recipe Genie/README.md
  public/Recipe Genie/index.html
  public/Recipe Genie/package-lock.json
  public/Recipe Genie/package.json
  public/Recipe Genie/postcss.config.js
  public/Recipe Genie/src/App.jsx
  public/Recipe Genie/src/components/search.jsx
  public/Recipe Genie/src/index.css
  public/Recipe Genie/src/main.jsx
  public/Recipe Genie/src/pages/Category.jsx
  public/Recipe Genie/src/pages/Home.jsx
  public/Recipe Genie/src/pages/Meal.jsx
  public/Recipe Genie/src/pages/RandomMeal.jsx
  public/Recipe Genie/tailwind.config.js
  public/Recipe Genie/vite.config.js
  public/index.html
Labels: enhancement, VSoC'24, HARD

#143 Improved styles of text to voice converter
  public/TextToVoiceConverter/index.html
  public/TextToVoiceConverter/styles.css
Labels: enhancement, VSoC'24, EASY

#142 E commerce cart update
  public/e-commerce_cart/LICENSE
  public/e-commerce_cart/README.md
  public/e-commerce_cart/images_used/abd.png
  public/e-commerce_cart/images_used/cart_icon.png
  public/e-commerce_cart/images_used/cristiano ronal 1.png
  public/e-commerce_cart/images_used/cross.png
  public/e-commerce_cart/images_used/giannis antetok 1.png
  public/e-commerce_cart/images_used/hero_shoe.png
  public/e-commerce_cart/images_used/home_icon.png
  public/e-commerce_cart/images_used/ishowspeed shoe 1.png
  public/e-commerce_cart/images_used/kobe bryant sho 0.png
  public/e-commerce_cart/images_used/messi shoes 0.png
  public/e-commerce_cart/images_used/nike jordans 0.png
  public/e-commerce_cart/images_used/profile_icon.png
  public/e-commerce_cart/images_used/search_icon.png
  public/e-commerce_cart/images_used/virat_kohli.png
  public/e-commerce_cart/index.css
  public/e-commerce_cart/index.html
  public/e-commerce_cart/index.js
  public/index.html
Labels: documentation, enhancement, VSoC'24, MEDIUM

#147 Movie Search engine
  public/index.html
  public/movie search/index.html
  public/movie search/preview.png
  public/movie search/script.js
  public/movie search/styles.css
Labels: enhancement, VSoC'24, MEDIUM

#149 Enhanced Budget Tracker: Detailed Categories and Visual Insights
  public/Budget Tracker/index.html
  public/Budget Tracker/script.js
  public/Budget Tracker/style.css
Labels: documentation, VSoC'24, MEDIUM, IN-PROGRESS

#139 Unit Tests for Climate Data Parsing Module
  public/ClimaCode 2.0/index.html
  public/ClimaCode 2.0/main.js
  public/ClimaCode 2.0/style.css
  public/index.html
Labels: enhancement, good first issue, VSoC'24, MEDIUM

#160 gave animation in ping pong game
  public/Palindrome_Generator/index.html
  public/Palindrome_Generator/script.js
  public/Palindrome_Generator/style.css
  public/ping/script.js
  public/ping/style.css
Labels: documentation, VSoC'24, MEDIUM

#155 Upgrading Vanilla JavaScript Calculator to Include Scientific Functions
  .vscode/settings.json
  public/Vanilla-JavaScript-Calculator-master/img/download (1).png
  public/Vanilla-JavaScript-Calculator-master/index.html
  public/Vanilla-JavaScript-Calculator-master/script.js
  public/Vanilla-JavaScript-Calculator-master/styles.css
Labels: documentation, VSoC'24, MEDIUM

#161 add pastebin
  public/index.html
  public/pastebin/.gitignore
  public/pastebin/.npmrc
  public/pastebin/.prettierignore
  public/pastebin/.prettierrc
  public/pastebin/README.md
  public/pastebin/package.json
  public/pastebin/postcss.config.js
  public/pastebin/schema.sql
  public/pastebin/src/app.css
  public/pastebin/src/app.d.ts
  public/pastebin/src/app.html
  public/pastebin/src/lib/index.ts
  public/pastebin/src/lib/pastes.ts
  public/pastebin/src/lib/themeSettings.ts
  public/pastebin/src/lib/types.d.ts
  public/pastebin/src/routes/+layout.svelte
  public/pastebin/src/routes/+page.svelte
  public/pastebin/src/routes/Header.svelte
  public/pastebin/src/routes/api/paste/+server.ts
  public/pastebin/src/routes/api/paste/[id]/+server.ts
  public/pastebin/src/routes/paste/[paste_id]/+error.svelte
  public/pastebin/src/routes/paste/[paste_id]/+page.svelte
  public/pastebin/src/routes/paste/[paste_id]/+page.ts
  public/pastebin/src/routes/paste/new/+page.svelte
  public/pastebin/static/Exo2-Medium.ttf
  public/pastebin/static/KodeMono-Regular.ttf
  public/pastebin/static/SegoeUI.ttf
  public/pastebin/static/favicon.png
  public/pastebin/static/preview.png
  public/pastebin/static/slash-square.svg
  public/pastebin/static/slash-square.svg:Zone.Identifier
  public/pastebin/svelte.config.js
  public/pastebin/tailwind.config.js
  public/pastebin/tsconfig.json
  public/pastebin/vite.config.ts
  public/pastebin/yarn.lock
  public/url_shortener/README.md
Labels: documentation, enhancement, VSoC'24, HARD

#174 updated README
  .all-contributorsrc
  README.md
Labels: documentation, VSoC'24, MEDIUM

#175 Adding social media glowing icons
  public/Social Media Glowing/index.html
  public/Social Media Glowing/style.css
  public/index.html
Labels: enhancement, VSoC'24, MEDIUM

#182 Country Capital Quiz Game
  public/Country Quiz Game/capitals.csv
  public/Country Quiz Game/index.js
  public/Country Quiz Game/package-lock.json
  public/Country Quiz Game/package.json
  public/Country Quiz Game/public/images/background.jpg
  public/Country Quiz Game/public/styles/main.css
  public/Country Quiz Game/readme
  public/Country Quiz Game/views/index.ejs
Labels: enhancement, VSoC'24, HARD

#178 Implement Responsive Design for Music Player
  public/Music App/index.html
  public/Music App/script.js
  public/Music App/style.css
  public/index.html
Labels: enhancement, VSoC'24, HARD

#186 Update issue templates
  .github/ISSUE_TEMPLATE/custom.md
Labels: documentation, VSoC'24, EASY

#189 Blog Page added
  public/Blog Page/index.html
  public/Blog Page/script.js
  public/index.html
Labels: enhancement, VSoC'24, EASY

#191 Email Validator project file update
  public/email validator/index.html
Labels: documentation, enhancement, VSoC'24, EASY, 1-POINT

#194 Hologram Button for Enhanced User Interaction
  public/Holo Button/index.html
  public/Holo Button/main.js
  public/Holo Button/style.css
  public/index.html
Labels: enhancement, good first issue, VSoC'24, MEDIUM

#197 image to text app
  public/Image-To-Text-App/index.html
  public/Image-To-Text-App/script.js
  public/index.html
Labels: documentation, enhancement, VSoC'24, MEDIUM

#205 changes
  public/AI ChatBot/Readme.md
  public/AI ChatBot/chatbot.html
  public/AI ChatBot/image.png
  public/AI ChatBot/shot1.png
  public/AI ChatBot/shot2.png
  public/AI ChatBot/shot3.png
  public/AI ChatBot/style.css
Labels: documentation, enhancement, VSoC'24, MEDIUM

#200 Planet Research Website
  public/Solar System Explorer in CSS only haml/style.css
  public/Solar System Explorer in CSS only haml/style.scss
  public/Solar System Explorer in CSS only haml/template.haml
  public/Solar System Explorer in CSS only haml/template.html
  public/index.html
Labels: documentation, enhancement, VSoC'24, BONUS
