Repository dhairyagothi/100_days_100_web_project, pull requests merged in 2024-07, with the labels that each got.

#208 zomato-clone-website
  public/index.html
  public/zomato-clone/accordion.js
  public/zomato-clone/app.css
  public/zomato-clone/explore.css
  public/zomato-clone/footer.css
  public/zomato-clone/images/favicon.ico
  public/zomato-clone/images/india.png
  public/zomato-clone/images/logo.png
  public/zomato-clone/index.css
  public/zomato-clone/main.css
  public/zomato-clone/nav.css
  public/zomato-clone/top.css
  public/zomato-clone/zomato.html
Labels: documentation, enhancement, VSoC'24, HARD

#204 GitHub profile find project update file index.html
  public/github_profile_finder/.gitignore
  public/github_profile_finder/Images/android-chrome-192x192.png
  public/github_profile_finder/Images/android-chrome-512x512.png
  public/github_profile_finder/Images/apple-touch-icon.png
  public/github_profile_finder/Images/company-icon.svg
  public/github_profile_finder/Images/favicon-16x16.png
  public/github_profile_finder/Images/favicon-32x32.png
  public/github_profile_finder/Images/favicon.ico
  public/github_profile_finder/Images/location-icon.svg
  public/github_profile_finder/Images/moon-icon.svg
  public/github_profile_finder/Images/search-icon.svg
  public/github_profile_finder/Images/site.webmanifest
  public/github_profile_finder/Images/sun-icon.svg
  public/github_profile_finder/Images/twitter-icon.svg
  public/github_profile_finder/Images/website-icon.svg
  public/github_profile_finder/README.md
  public/github_profile_finder/index.html
  public/github_profile_finder/package-lock.json
  public/github_profile_finder/package.json
  public/github_profile_finder/public/favicon.ico
  public/github_profile_finder/public/index.html
  public/github_profile_finder/public/logo192.png
  public/github_profile_finder/public/logo512.png
  public/github_profile_finder/public/manifest.json
  public/github_profile_finder/public/robots.txt
  public/github_profile_finder/script.js
  public/github_profile_finder/src/App.css
  public/github_profile_finder/src/App.js
  public/github_profile_finder/src/App.test.js
  public/github_profile_finder/src/components/Finder.jsx
  public/github_profile_finder/src/components/Profile.jsx
  public/github_profile_finder/src/components/Repo.jsx
  public/github_profile_finder/src/components/RepoDetails.jsx
  public/github_profile_finder/src/index.css
  public/github_profile_finder/src/index.js
  public/github_profile_finder/src/logo.svg
  public/github_profile_finder/src/reportWebVitals.js
  public/github_profile_finder/src/setupTests.js
  public/github_profile_finder/style.css
  public/github_profile_finder/tailwind.config.js
Labels: documentation, enhancement, VSoC'24, MEDIUM

#214 flask authN application
  public/flask_auth_app/.gitignore
  public/flask_auth_app/README.md
  public/flask_auth_app/app.py
  public/flask_auth_app/requirements.txt
  public/flask_auth_app/templates/home.html
  public/flask_auth_app/templates/login.html
  public/flask_auth_app/templates/protected.html
  public/flask_auth_app/templates/signup.html
  public/index.html
Labels: documentation, enhancement, VSoC'24, HARD

#218 Typewriter Project with Improved User Interactivity and Customization
  public/typewriter/typewriter.css
  public/typewriter/typewriter.html
  public/typewriter/typewriter.js
Labels: documentation, enhancement, VSoC'24, MEDIUM

#216 updated buttons stylings like padding and border-radius.
  public/TO_DO_LIST/todolist.css
Labels: documentation, enhancement, VSoC'24, EASY

#209 Cube Game
  public/The Cube/index.html
  public/The Cube/main.js
  public/The Cube/style.css
  public/The Cube/style.sass
  public/index.html
Labels: documentation, enhancement, VSoC'24, MEDIUM

#210 blog-website-added
  public/blog/assets/10165944.jpg
  public/blog/assets/4401280.jpg
  public/blog/assets/61695-499594106_medium.mp4
  public/blog/assets/arrow_6353601.png
  public/blog/assets/cssGrid.jpg
  public/blog/assets/discord.png
  public/blog/assets/female1.jpg
  public/blog/assets/female2.jpg
  public/blog/assets/github.png
  public/blog/assets/icons8-facebook-96.png
  public/blog/assets/icons8-instagram-96.png
  public/blog/assets/icons8-youtube-96.png
  public/blog/assets/javascript.jpg
  public/blog/assets/linkedin.png
  public/blog/assets/male1.jpg
  public/blog/assets/male2.jpg
  public/blog/assets/male3.jpg
  public/blog/assets/react.jpg
  public/blog/assets/responsiveWeb.jpg
  public/blog/assets/writer_6543533.png
  public/blog/blog-script.js
  public/blog/blog.html
  public/blog/main.html
  public/blog/script.js
  public/blog/style.css
  public/blog/styles.css
  public/index.html
Labels: enhancement, VSoC'24, HARD

#228 #225
  public/indianflag/flag.css
  public/indianflag/flag.html
Labels: documentation, enhancement, VSoC'24, EASY

#217 added features of date and history
  public/Medical_App/index.html
  public/Medical_App/script.js
  public/Medical_App/styles.css
Labels: documentation, VSoC'24, MEDIUM

#227 plant-website-enhanced
  public/plantwebsite/images/indoor-plants_5451442.png
  public/plantwebsite/plant.css
  public/plantwebsite/plant.html
  public/plantwebsite/script.js
Labels: documentation, enhancement, VSoC'24, MEDIUM

#229 Enhancement: Add 3D Responsive Rotating Card
  public/3d cards/Images/img1.jpg
  public/3d cards/Images/img2.jpg
  public/3d cards/Images/img3.jpg
  public/3d cards/Images/img4.jpg
  public/3d cards/Images/img5.jpg
  public/3d cards/Images/img6.jpg
  public/3d cards/Images/img7.jpg
  public/3d cards/Images/img8.jpg
  public/3d cards/index.html
  public/3d cards/style.css
  public/index.html
Labels: documentation, enhancement, VSoC'24, MEDIUM

#231 updated hover effects and cursor pointer.
  public/Background-Image-sider/slider.css
  public/Background-Image-sider/slider.html
Labels: documentation, enhancement, VSoC'24, EASY

#221 Spotify clone project added
  public/index.html
  public/spotify-clone -project/cover.jpg
  public/spotify-clone -project/images/All Out 2010s.jpg
  public/spotify-clone -project/images/All Out 80s.jpg
  public/spotify-clone -project/images/Beats to think to.jpg
  public/spotify-clone -project/images/Chill Hits.jpg
  public/spotify-clone -project/images/Deep Focus.jpg
  public/spotify-clone -project/images/Focus Flow.jpg
  public/spotify-clone -project/images/Instrumental Study.jpg
  public/spotify-clone -project/images/Peaceful Piano.jpg
  public/spotify-clone -project/images/RapCaviar.jpg
  public/spotify-clone -project/images/Reading Adventure.jpg
  public/spotify-clone -project/images/Rock Classics.jpg
  public/spotify-clone -project/images/Spotify Logo.png
  public/spotify-clone -project/images/Spotify_favicon.png
  public/spotify-clone -project/images/The Sound of Bengaluru.jpg
  public/spotify-clone -project/images/The Sound of Chennai.jpg
  public/spotify-clone -project/images/The Sound of Delhi.jpg
  public/spotify-clone -project/images/The Sound of Hyderabad.jpg
  public/spotify-clone -project/images/The Sound of Kolkata.jpg
  public/spotify-clone -project/images/The Sound of Mumbai.jpg
  public/spotify-clone -project/images/Today_s Top Hits.jpg
  public/spotify-clone -project/images/Viva Latino.jpg
  public/spotify-clone -project/images/Workday Lounge.jpg
  public/spotify-clone -project/index.html
  public/spotify-clone -project/styles.css
Labels: documentation, enhancement, VSoC'24, MEDIUM

#233 Snake game
  public/snake_game/index.css
  public/snake_game/index.html
  public/snake_game/index.js
  public/snake_game/script.js
  public/snake_game/style.css
Labels: documentation, enhancement, VSoC'24, HARD

#235 Indian flag our Pride
  public/indianflag/flag.css
  public/indianflag/flag.html
  public/indianflag/img/ashokchakr.gif
Labels: enhancement, VSoC'24, MEDIUM

#239 update the UI of password generator project
  public/Password_Generator/assets/copy.svg
  public/Password_Generator/assets/favicon.ico
  public/Password_Generator/index.html
  public/Password_Generator/script.js
  public/Password_Generator/style.css
Labels: documentation, enhancement, VSoC'24, MEDIUM

#241 Add Speech-to-Text Feature to Text-to-Voice Converter Project
  public/AI ChatBot/chatbot.html
  public/AI ChatBot/style.css
  public/TextToVoiceConverter/index.html
  public/TextToVoiceConverter/script.js
  public/TextToVoiceConverter/styles.css
Labels: documentation, enhancement, VSoC'24, HARD

#243 Added navbar to index.html with required CSS and JS
  public/github.png
  public/github1.png
  public/home.css
  public/home.js
  public/index.html
  public/logo.png
  public/logo1.png
Labels: documentation, enhancement, good first issue, VSoC'24, MEDIUM

#252 Update style.css
  public/Social Media Glowing/style.css
Labels: documentation, enhancement, VSoC'24, EASY

#247 add project Insect_Catch_Game
  public/Insect-Catch-Game/index.html
  public/Insect-Catch-Game/script.js
  public/Insect-Catch-Game/style.css
  public/index.html
Labels: documentation, enhancement, good first issue, VSoC'24, MEDIUM

#244 Footer_small the icons of contributors
  public/Img/Atharva.jpg
  public/Img/Ayushswirlon.png
  public/Img/Bhagwan.jpg
  public/Img/Dhairya.jpg
  public/Img/MonishRaman.jpg
  public/Img/Suhaina.png
  public/Img/Vansh.jpg
  public/Img/externef.jpg
  public/Img/github.png
  public/Img/kom-senapati.jpg
  public/Img/twitter.png
  public/Img/yaser-123.jpg
  public/home.css
  public/index.html
Labels: documentation, enhancement, VSoC'24, MEDIUM

#256 Adding a Navbar in Website
  public/index.html
Labels: documentation, enhancement, VSoC'24, HARD

#257 Interactive 3D Social Media Icon
  public/Social Media Glowing/glow.css
  public/Social Media Glowing/index.html
Labels: enhancement, good first issue, VSoC'24, EASY

#255 Add word dictionary project
  public/Word_dictionary/app.js
  public/Word_dictionary/index.html
  public/Word_dictionary/style.css
Labels: documentation, enhancement, VSoC'24, MEDIUM

#254 Quotely Laughs
  public/Quotely-Laughs/index.html
  public/Quotely-Laughs/script.js
  public/index.html
Labels: documentation, enhancement, VSoC'24, MEDIUM

#272 Updated home.css
  public/home.css
Labels: documentation, VSoC'24, HARD

#271 solve bug of qr-generator project
  public/qr generator/qr.css
  public/qr generator/qr.html
  public/qr generator/qr.js
Labels: documentation, VSoC'24, MEDIUM

#266 Enhanced Notes app
  public/notes-app/index.html
  public/notes-app/script.js
  public/notes-app/style.css
Labels: documentation, enhancement, VSoC'24, HARD

#270 Update index.html
  public/index.html
Labels: documentation, VSoC'24, 1-POINT

#278 project: Contact Book
  public/Contact Book/.gitignore
  public/Contact Book/README.md
  public/Contact Book/app.py
  public/Contact Book/requirements.txt
  public/Contact Book/templates/base.html
  public/Contact Book/templates/contact_form.html
  public/Contact Book/templates/dashboard.html
  public/Contact Book/templates/home.html
  public/Contact Book/templates/login.html
  public/Contact Book/templates/register.html
  public/index.html
Labels: documentation, enhancement, VSoC'24, HARD

#277 Added Voice Search Feature and UI Design Enhancement
  public/Word_dictionary/app.js
  public/Word_dictionary/index.html
  public/Word_dictionary/style.css
Labels: documentation, enhancement, VSoC'24, MEDIUM

#261 add project Candy_Crush_Game
  public/Candy_Crush_Game/background.jpg
  public/Candy_Crush_Game/images/Blue-Striped-Horizontal.png
  public/Candy_Crush_Game/images/Blue-Striped-Vertical.png
  public/Candy_Crush_Game/images/Blue-Wrapped.png
  public/Candy_Crush_Game/images/Blue.png
  public/Candy_Crush_Game/images/Choco.png
  public/Candy_Crush_Game/images/Green-Striped-Horizontal.png
  public/Candy_Crush_Game/images/Green-Striped-Vertical.png
  public/Candy_Crush_Game/images/Green-Wrapped.png
  public/Candy_Crush_Game/images/Green.png
  public/Candy_Crush_Game/images/Orange-Striped-Horizontal.png
  public/Candy_Crush_Game/images/Orange-Striped-Vertical.png
  public/Candy_Crush_Game/images/Orange-Wrapped.png
  public/Candy_Crush_Game/images/Orange.png
  public/Candy_Crush_Game/images/Purple-Striped-Horizontal.png
  public/Candy_Crush_Game/images/Purple-Striped-Vertical.png
  public/Candy_Crush_Game/images/Purple-Wrapped.png
  public/Candy_Crush_Game/images/Purple.png
  public/Candy_Crush_Game/images/Red-Striped-Horizontal.png
  public/Candy_Crush_Game/images/Red-Striped-Vertical.png
  public/Candy_Crush_Game/images/Red-Wrapped.png
  public/Candy_Crush_Game/images/Red.png
  public/Candy_Crush_Game/images/Yellow-Striped-Horizontal.png
  public/Candy_Crush_Game/images/Yellow-Striped-Vertical.png
  public/Candy_Crush_Game/images/Yellow-Wrapped.png
  public/Candy_Crush_Game/images/Yellow.png
  public/Candy_Crush_Game/images/blank.png
  public/Candy_Crush_Game/index.html
  public/Candy_Crush_Game/script.js
  public/Candy_Crush_Game/style.css
  public/index.html
Labels: documentation, enhancement, VSoC'24, MEDIUM

#274 Feat : Added Stock profit calculator as a Day-72 Project
  public/Stock-Profit-Calculator/README.md
  public/Stock-Profit-Calculator/assets/background.jpg
  public/Stock-Profit-Calculator/assets/stock_calci.jpg
  public/Stock-Profit-Calculator/index.html
  public/Stock-Profit-Calculator/script.js
  public/Stock-Profit-Calculator/style.css
  public/index.html
Labels: documentation, VSoC'24, HARD

#282 Designed logo and Added favicon
  public/favicon.png
  public/index.html
Labels: documentation, VSoC'24, MEDIUM

#287 add project Code-space- jump-game project
  public/code-jump-space-game/doodlejumpbg.png
  public/code-jump-space-game/doodler-left.png
  public/code-jump-space-game/doodler-right.png
  public/code-jump-space-game/index.html
  public/code-jump-space-game/platform-broken.png
  public/code-jump-space-game/platform.png
  public/code-jump-space-game/script.js
  public/code-jump-space-game/style.css
  public/index.html
Labels: documentation, enhancement, VSoC'24, MEDIUM

#292 fixing readme
  .github/workflows/add-contributors.yml
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  README.md
Labels: documentation, help wanted, VSoC'24, MEDIUM

#288 Feat : Added Cryptocurrency calculator as DAY-75 Project
  public/Cryptocurrency-Calculator/README.md
  public/Cryptocurrency-Calculator/assets/background.jpg
  public/Cryptocurrency-Calculator/index.html
  public/Cryptocurrency-Calculator/script.js
  public/Cryptocurrency-Calculator/style.css
  public/index.html
Labels: documentation, enhancement, VSoC'24, MEDIUM

#291 Added Animated Search-bar
  public/Animated Searchbar/app.js
  public/Animated Searchbar/index.html
  public/Animated Searchbar/style.css
  public/Word_dictionary/app.js
  public/Word_dictionary/index.html
  public/index.html
Labels: documentation, enhancement, good first issue, VSoC'24, MEDIUM

#302 Updated features in Stock_Profit_Calculator
  public/Stock-Profit-Calculator/index.html
  public/Stock-Profit-Calculator/script.js
  public/Stock-Profit-Calculator/style.css
Labels: documentation, MEDIUM

#299 Update index.html with Day 77: Rock Paper Scissors Game.
  public/index.html
Labels: documentation, VSoC'24, HARD

#303 Create readme.md
  public/Discord project/readme.md
  public/Img/Atharva.jpg
  public/Img/Ayushswirlon.png
  public/Img/Bhagwan.jpg
  public/Img/Dhairya.jpg
  public/Img/MonishRaman.jpg
  public/Img/Suhaina.png
  public/Img/Vansh.jpg
  public/Img/externef.jpg
  public/Img/github.png
  public/Img/kom-senapati.jpg
  public/Img/twitter.png
  public/Img/yaser-123.jpg
  public/gmail_nodemailer/readme.md
Labels: documentation, VSoC'24, HARD, Urgent

#304 Added Sign-up page in Marketing Website
  public/index.html
  public/marketing_website/index.html
  public/marketing_website/index2.html
Labels: documentation, enhancement, VSoC'24, MEDIUM

#306 Feature Update : Enhanced CAPTCHA Options
  public/captcha/captcha.css
  public/captcha/captcha.html
  public/captcha/captcha.js
Labels: documentation, VSoC'24, HARD

#309 Enhanced Qr Generator
  public/qr generator/qr.css
  public/qr generator/qr.html
  public/qr generator/qr.js
Labels: documentation, enhancement, VSoC'24, MEDIUM

#312 feat: search bar
  public/home.css
  public/index.html
Labels: documentation, enhancement, VSoC'24, HARD
