Repository dhairyagothi/100_days_100_web_project, pull requests merged in 2025-01, with the labels that each got.

#330 Linkedin clone
  README.md
  index.html
  public/Linkedin-Clone/images/chat.png
  public/Linkedin-Clone/images/clap.png
  public/Linkedin-Clone/images/comment.png
  public/Linkedin-Clone/images/connect.png
  public/Linkedin-Clone/images/cover-pic.png
  public/Linkedin-Clone/images/display.png
  public/Linkedin-Clone/images/down-arrow.png
  public/Linkedin-Clone/images/event.png
  public/Linkedin-Clone/images/feedback.png
  public/Linkedin-Clone/images/google.png
  public/Linkedin-Clone/images/group.png
  public/Linkedin-Clone/images/hashtag.png
  public/Linkedin-Clone/images/help.png
  public/Linkedin-Clone/images/home.png
  public/Linkedin-Clone/images/items.png
  public/Linkedin-Clone/images/jobs.png
  public/Linkedin-Clone/images/like.png
  public/Linkedin-Clone/images/logo.png
  public/Linkedin-Clone/images/logout.png
  public/Linkedin-Clone/images/love.png
  public/Linkedin-Clone/images/message.png
  public/Linkedin-Clone/images/mi-logo.png
  public/Linkedin-Clone/images/microsoft.png
  public/Linkedin-Clone/images/mit.png
  public/Linkedin-Clone/images/more.png
  public/Linkedin-Clone/images/network.png
  public/Linkedin-Clone/images/north.png
  public/Linkedin-Clone/images/notification.png
  public/Linkedin-Clone/images/photo.png
  public/Linkedin-Clone/images/post-image-1.png
  public/Linkedin-Clone/images/post-image-2.png
  public/Linkedin-Clone/images/post-image-3.png
  public/Linkedin-Clone/images/post-image-4.png
  public/Linkedin-Clone/images/premium.png
  public/Linkedin-Clone/images/recent.png
  public/Linkedin-Clone/images/right-arrow.png
  public/Linkedin-Clone/images/search.png
  public/Linkedin-Clone/images/send.png
  public/Linkedin-Clone/images/setting.png
  public/Linkedin-Clone/images/share.png
  public/Linkedin-Clone/images/slack.png
  public/Linkedin-Clone/images/stanford.png
  public/Linkedin-Clone/images/thumbsup.png
  public/Linkedin-Clone/images/user-1.png
  public/Linkedin-Clone/images/user-2.png
  public/Linkedin-Clone/images/user-3.png
  public/Linkedin-Clone/images/user-4.png
  public/Linkedin-Clone/images/user-5.png
  public/Linkedin-Clone/images/video.png
  public/Linkedin-Clone/index.html
  public/Linkedin-Clone/style.css
Labels: enhancement, INTERMEDIATE, SWOC

#337 Add Logos to the Navbar and Fix Footer CSS
  GitHub.png
  home.css
  icons8-working-with-a-laptop-48.png
  icons8-working-with-a-laptop-96.png
  index.html
  package-lock.json
  twitter_x_new_logo_x_rounded_icon_256078.svg
Labels: enhancement, BEGINNER, SWOC

#335 #328 Done, A Complete Revamp Of The UI
  bulma.js
  home.css
  home.js
  index.css
  index.html
  index.js
Labels: enhancement, ADVANCE, SWOC

#341 Fixes the issue of LinkedIn clone Navbar
  public/Linkedin-Clone/index.html
  public/Linkedin-Clone/style.css
Labels: BEGINNER, SWOC

#350 contributor page added to website
  contributors/contributor.css
  contributors/contributor.html
  contributors/contributor.js
  index.html
Labels: enhancement, INTERMEDIATE, SWOC

#356 Smaller Screen Issue Fixed
  home.css
  index.html
  public/TO_DO_LIST/todolist.css
  public/TO_DO_LIST/todolist.html
Labels: enhancement, INTERMEDIATE, SWOC

#357 added ResumeStudio project
  index.js
  public/ResumeStudio/index.html
  public/ResumeStudio/script.js
  public/ResumeStudio/style.css
Labels: enhancement, ADVANCE, SWOC

#358 #353 issue solved top scroll button
  .vscode/settings.json
  index.html
Labels: enhancement, good first issue, INTERMEDIATE, SWOC

#359 Fixes the issue on smaller screen size
  home.css
  index.css
  index.html
Labels: BEGINNER, SWOC

#361 Updated UI with new design and color scheme
  public/password manager/style.css
Labels: enhancement, BEGINNER, SWOC

#367 Add Reset Button to Memory Game
  public/MemoryGame/index.html
  public/MemoryGame/script.js
  public/MemoryGame/style.css
  public/Missionaries&Cannibals/script.js
  public/Missionaries&Cannibals/styles.css
  public/snake_game/style.css
Labels: enhancement, BEGINNER, SWOC

#370 Updated Footer Section
  images/1736231291121.png
  index.html
Labels: enhancement, good first issue, INTERMEDIATE, SWOC

#372 Added contributors page to navbar itself and added a logo according t…
  index.html
  index.js
Labels: enhancement, BEGINNER, SWOC

#379 Fav icon change
  index.html
  public/fav.ico
  public/favv.png
Labels: BEGINNER, SWOC

#390 CountDown Timer Fixed
  index.js
  public/CountDown Timer/index.html
  public/CountDown Timer/script.js
  public/CountDown Timer/style.css
Labels: enhancement, BEGINNER, SWOC

#371 Added Self improvement project
  public/Self-Improvement/README.md
  public/Self-Improvement/car.jpg
  public/Self-Improvement/git.jpg
  public/Self-Improvement/index.html
  public/Self-Improvement/insta.jpg
  public/Self-Improvement/linked.jpg
  public/Self-Improvement/responsive.css
  public/Self-Improvement/script.js
  public/Self-Improvement/style.css
Labels: INTERMEDIATE, SWOC

#392 UI Enhancements for Missionary and Cannibals Game
  public/Missionaries&Cannibals/index.html
  public/Missionaries&Cannibals/script.js
  public/Missionaries&Cannibals/styles.css
Labels: BEGINNER, SWOC, points-assignment-done

#394 Simon says game
  index.js
  public/Simon_Says_Game/index.html
  public/Simon_Says_Game/script.js
  public/Simon_Says_Game/style.css
Labels: enhancement, good first issue, INTERMEDIATE, SWOC

#398 love calculator is added
  images/82.png
  index.js
  public/Love-Calculator/index.html
  public/Love-Calculator/script.js
  public/Love-Calculator/style.css
Labels: INTERMEDIATE, SWOC, points-assignment-done

#396 Exchange currency
  index.js
  package-lock.json
  public/Exchange_Currency/app.js
  public/Exchange_Currency/data.js
  public/Exchange_Currency/index.html
  public/Exchange_Currency/style.css
Labels: INTERMEDIATE, SWOC, points-assignment-done

#417 the UI is done
  desktop.ini
  public/Maze-Game-main/index.html
  public/Maze-Game-main/style.css
Labels: BEGINNER, SWOC, points-assignment-done

#419 Fix: Make Navbar Sticky
  index.html
Labels: enhancement, BEGINNER, SWOC

#427 after adding the list elements earlier it was not good looking in mob…
  public/TO_DO_LIST/todolist.css
Labels: BEGINNER, SWOC, points-assignment-done

#434 Add hover effect to amazon clone.
  public/Amazon_Clone/style.css
Labels: BEGINNER, SWOC

#437 Added timer feature to analog clock and improved UI
  public/AnalogClock/index.css
  public/AnalogClock/index.html
  public/AnalogClock/index.js
  public/AnalogClock/timer.mp3
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#440 Updated the logos color
  index.html
Labels: enhancement, BEGINNER, SWOC, points-assignment-done

#442 Update index.html
  index.html
Labels: enhancement, BEGINNER, SWOC, points-assignment-done

#445 Fixed Pro-27 Memory Game
  public/MemoryGame/index.html
  public/MemoryGame/script.js
  public/MemoryGame/style.css
Labels: INTERMEDIATE, SWOC, points-assignment-done

#446 Fixed Amazon Clone
  public/Amazon_Clone/amazon_logo.png
  public/Amazon_Clone/box1_image.jpg
  public/Amazon_Clone/box2_image.jpg
  public/Amazon_Clone/box3_image.jpg
  public/Amazon_Clone/box4_image.jpg
  public/Amazon_Clone/box5_image.jpg
  public/Amazon_Clone/box6_image.jpg
  public/Amazon_Clone/box7_image.jpg
  public/Amazon_Clone/box8_image.jpg
  public/Amazon_Clone/hero_image.jpg
  public/Amazon_Clone/index.html
  public/Amazon_Clone/style.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#457 updated calculator code
  public/Vanilla-JavaScript-Calculator-master/index.html
  public/Vanilla-JavaScript-Calculator-master/script.js
  public/Vanilla-JavaScript-Calculator-master/styles.css
Labels: enhancement, INTERMEDIATE, SWOC

#418 3D Profile Card using HTML & CSS
  index.js
  public/3d profile Card/Images/background.jpg
  public/3d profile Card/Images/waving-hand.png
  public/3d profile Card/index.html
  public/3d profile Card/style.css
Labels: Changes needed, INTERMEDIATE, SWOC, points-assignment-done

#456 BMI-calculator
  public/BMI_Calculator/index.html
  public/BMI_Calculator/script.js
  public/BMI_Calculator/style.css
Labels: enhancement, BEGINNER, SWOC

#410 Added Social-media-&-page-links
  index.html
  index.js
Labels: enhancement, BEGINNER, SWOC, points-assignment-pending

#430 Changes in UI of to-do list
  .vscode/launch.json
  public/TO_DO_LIST/todolist.css
  public/TO_DO_LIST/todolist.html
  public/TO_DO_LIST/todolist.js
Labels: enhancement, INTERMEDIATE, SWOC

#461 DONE PARALLE_X_WEBSITE
  parallal.css
  parallal.html
  parallal.js
Labels: INTERMEDIATE, SWOC, points-assignment-done

#462 New Amazon clone with working Functions
  public/New-AmazonClone/Readme.md
  public/New-AmazonClone/images/abc.txt
  public/New-AmazonClone/images/acb.jpg
  public/New-AmazonClone/images/amazon_logo.png
  public/New-AmazonClone/images/banner.jpg
  public/New-AmazonClone/images/box1_image.jpg
  public/New-AmazonClone/images/box2_image.jpg
  public/New-AmazonClone/images/box3_image.jpg
  public/New-AmazonClone/images/box4_image.jpg
  public/New-AmazonClone/images/box5_image.jpg
  public/New-AmazonClone/images/box6_image.jpg
  public/New-AmazonClone/images/box7_image.jpg
  public/New-AmazonClone/images/box8_image.jpg
  public/New-AmazonClone/images/hero_image.jpg
  public/New-AmazonClone/images/india.png
  public/New-AmazonClone/index.html
  public/New-AmazonClone/script.js
  public/New-AmazonClone/style.css
Labels: enhancement, INTERMEDIATE, SWOC

#463 Add Resume and pause
  public/progress_bar/progress_bar.js
Labels: INTERMEDIATE, SWOC

#473 Enhanced UI for Missionaries and Cannibals Game
  public/Missionaries&Cannibals/index.html
  public/Missionaries&Cannibals/script.js
  public/Missionaries&Cannibals/styles.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#467 Add Project
  public/text-to-readme/.gitignore
  public/text-to-readme/README.md
  public/text-to-readme/package-lock.json
  public/text-to-readme/package.json
  public/text-to-readme/public/index.html
  public/text-to-readme/src/App.css
  public/text-to-readme/src/App.js
  public/text-to-readme/src/index.js
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#479 Added catchy insect game
  public/game/index.html
  public/game/script.js
  public/game/style.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#485 Medical App
  public/Medical_App/feedback.html
  public/Medical_App/index.html
  public/Medical_App/pngtree-medical-device-line-draft-border-png-image_2392872.jpg
  public/Medical_App/script.js
  public/Medical_App/styles.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#492 Added animated CSS
  public/WORDLE/assets/css/style.css
Labels: enhancement, BEGINNER, SWOC, points-assignment-done

#493 IMAGE_SLIDER DONE
  slider.css
  slider.html
  slider.js
Labels: enhancement, BEGINNER, SWOC, points-assignment-done

#502 FIX 2048 game UI change
  public/2048_game/index.html
  public/2048_game/script.js
  public/2048_game/style.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#483 Improvement/css
  .vscode/settings.json
  home.css
  index.css
  index.html
  public/TicTacToe/style.css
  public/Weather Forcasting/style.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#499 Image Search Engine Added
  .DS_Store
  index.js
  public/Image Search Engine/index.html
  public/Image Search Engine/script.js
  public/Image Search Engine/style.css
Labels: enhancement, INTERMEDIATE, SWOC

#453 Add a new project-Lights Out
  index.js
  public/Lights_Out_Puzzle/index.html
  public/Lights_Out_Puzzle/script.js
  public/Lights_Out_Puzzle/styles.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-pending

#514 Cricket Code
  public/cricket/index.html
  public/cricket/script.js
  public/cricket/stadiumimage.webp
  public/cricket/style.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#486 Add Breakout Game
  index.js
  public/Breakout game/index.html
  public/Breakout game/script.js
  public/Breakout game/styles.css
Labels: enhancement, ADVANCE, SWOC, points-assignment-done

#517 FIX, QR Code Generator QR Align In Center
  public/qr generator/qr.css
Labels: enhancement, BEGINNER, SWOC, points-assignment-done

#518 Add job
  .vscode/launch.json
  index.js
  public/Job dashboard/AllmediaLts.html
  public/Job dashboard/ITWorlds.html
  public/Job dashboard/ITinfosy.html
  public/Job dashboard/InfoStatics.html
  public/Job dashboard/image/css3-logo-png-transparent.png
  public/Job dashboard/image/html.webp
  public/Job dashboard/image/java.jpg
  public/Job dashboard/image/php.jpg
  public/Job dashboard/jobs.css
  public/Job dashboard/jobs.html
  public/Job dashboard/jobs.js
  public/Job dashboard/massIdea.html
  public/Job dashboard/softwareSolution.html
Labels: enhancement, ADVANCE, SWOC, points-assignment-done

#526 Updated Calculator css and js
  public/Vanilla-JavaScript-Calculator-master/img/download (1).png
  public/Vanilla-JavaScript-Calculator-master/index.html
  public/Vanilla-JavaScript-Calculator-master/script.js
  public/Vanilla-JavaScript-Calculator-master/styles.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#528 Changes in UI of Tic Tac Toe
  public/TicTacToe/index.html
  public/TicTacToe/style.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#525 Added new Project - N_Queen and also updated index.js file in Main
  index.js
  public/N_Queen/index.html
  public/N_Queen/script.js
  public/N_Queen/style.css
Labels: enhancement, ADVANCE, SWOC, points-assignment-done

#529 Add kowledge quiz app
  index.js
  public/knowledge quiz/app.css
  public/knowledge quiz/index1.html
  public/knowledge quiz/script.js
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#519 Added Voting Application Backend
  index.js
  public/Voting_Application_Backend/package-lock.json
  public/Voting_Application_Backend/server/.gitignore
  public/Voting_Application_Backend/server/VoteApp.drawio
  public/Voting_Application_Backend/server/db.js
  public/Voting_Application_Backend/server/jwt.js
  public/Voting_Application_Backend/server/models/candidate.js
  public/Voting_Application_Backend/server/models/user.js
  public/Voting_Application_Backend/server/package-lock.json
  public/Voting_Application_Backend/server/package.json
  public/Voting_Application_Backend/server/routes/candidateRoutes.js
  public/Voting_Application_Backend/server/routes/userRoutes.js
  public/Voting_Application_Backend/server/server.js
  public/package-lock.json
Labels: enhancement, ADVANCE, SWOC, points-assignment-done

#516 Add Editor and Markdown Feature
  package-lock.json
  public/text-to-readme/package-lock.json
  public/text-to-readme/package.json
  public/text-to-readme/src/App.css
  public/text-to-readme/src/App.js
  public/text-to-readme/src/components/alert/AlertBox.jsx
  public/text-to-readme/src/components/alert/alertbox.css
  public/text-to-readme/src/components/editor/Editor.jsx
  public/text-to-readme/src/components/editor/editor.css
  public/text-to-readme/src/components/navbar/Navbar.jsx
  public/text-to-readme/src/components/navbar/navbar.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#558 minimized the window size
  index.css
Labels: enhancement, BEGINNER, SWOC

#556 Text to case converter app added
  index.js
  public/Slide puzzle Game/1.jpg
  public/Slide puzzle Game/10.jpg
  public/Slide puzzle Game/2.jpg
  public/Slide puzzle Game/3.jpg
  public/Slide puzzle Game/4.jpg
  public/Slide puzzle Game/5.jpg
  public/Slide puzzle Game/6.jpg
  public/Slide puzzle Game/7.jpg
  public/Slide puzzle Game/8.jpg
  public/Slide puzzle Game/9.jpg
  public/Slide puzzle Game/img/logo.png
  public/Slide puzzle Game/index.html
  public/Slide puzzle Game/puzzle.css
  public/Slide puzzle Game/puzzle.js
  public/Textutils/.gitignore
  public/Textutils/README.md
  public/Textutils/package-lock.json
  public/Textutils/package.json
  public/Textutils/public/android-icon-192x192.png
  public/Textutils/public/favicon-16x16.png
  public/Textutils/public/favicon-32x32.png
  public/Textutils/public/favicon-96x96.png
  public/Textutils/public/favicon.ico
  public/Textutils/public/index.html
  public/Textutils/public/manifest.json
  public/Textutils/public/robots.txt
  public/Textutils/src/App.css
  public/Textutils/src/App.js
  public/Textutils/src/App.test.js
  public/Textutils/src/components/Alert.js
  public/Textutils/src/components/Navbar.js
  public/Textutils/src/components/TextForm.js
  public/Textutils/src/index.css
  public/Textutils/src/index.js
  public/Textutils/src/logo.svg
  public/Textutils/src/reportWebVitals.js
  public/Textutils/src/setupTests.js
  public/plantwebsite/plant.css
  public/plantwebsite/plant.html
Labels: enhancement, ADVANCE, SWOC, points-assignment-done

#512 update candy crush with new features
  index.js
  public/Candy_Crush_Game/index.html
  public/Candy_Crush_Game/script.js
  public/Candy_Crush_Game/style.css
Labels: enhancement, INTERMEDIATE, SWOC

#543 Add HangMan Game
  index.js
  public/HangmanGame/images/hangman-0.svg
  public/HangmanGame/images/hangman-1.svg
  public/HangmanGame/images/hangman-2.svg
  public/HangmanGame/images/hangman-3.svg
  public/HangmanGame/images/hangman-4.svg
  public/HangmanGame/images/hangman-5.svg
  public/HangmanGame/images/hangman-6.svg
  public/HangmanGame/images/lost.gif
  public/HangmanGame/images/victory.gif
  public/HangmanGame/index.html
  public/HangmanGame/script.js
  public/HangmanGame/style.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-pending

#560 Bachground-Slider
  .vscode/settings.json
  public/Background-Image-sider/images/Brooke-Holm.jpeg
  public/Background-Image-sider/images/Daniel.jpeg
  public/Background-Image-sider/images/Hannes-Becker4.jpg
  public/Background-Image-sider/images/Jennifer.avif
  public/Background-Image-sider/images/Tobias-Hagg.jpg
  public/Background-Image-sider/images/kai.jpg
  public/Background-Image-sider/slider.css
  public/Background-Image-sider/slider.html
Labels: INTERMEDIATE, SWOC, points-assignment-done

#561 Add HCL Color Generator Project
  index.js
  public/HCL Color Generator/index.html
  public/HCL Color Generator/script.js
  public/HCL Color Generator/style.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#563 Corrected the message box
  public/Maze-Game-main/style.css
Labels: enhancement, BEGINNER, SWOC, points-assignment-done

#568 Feat/add todolist react ts tailwind
  README.md
  index.js
  public/TodoList-React-TS-Tailwind/README.md
  public/TodoList-React-TS-Tailwind/bun.lockb
  public/TodoList-React-TS-Tailwind/eslint.config.js
  public/TodoList-React-TS-Tailwind/index.html
  public/TodoList-React-TS-Tailwind/package.json
  public/TodoList-React-TS-Tailwind/postcss.config.js
  public/TodoList-React-TS-Tailwind/public/vite.svg
  public/TodoList-React-TS-Tailwind/src/App.css
  public/TodoList-React-TS-Tailwind/src/App.tsx
  public/TodoList-React-TS-Tailwind/src/assets/react.svg
  public/TodoList-React-TS-Tailwind/src/components/Header.tsx
  public/TodoList-React-TS-Tailwind/src/components/Settings.tsx
  public/TodoList-React-TS-Tailwind/src/components/Todolist.tsx
  public/TodoList-React-TS-Tailwind/src/components/TodolistItem.css
  public/TodoList-React-TS-Tailwind/src/index.css
  public/TodoList-React-TS-Tailwind/src/main.tsx
  public/TodoList-React-TS-Tailwind/src/vite-env.d.ts
  public/TodoList-React-TS-Tailwind/tailwind.config.js
  public/TodoList-React-TS-Tailwind/tsconfig.app.json
  public/TodoList-React-TS-Tailwind/tsconfig.json
  public/TodoList-React-TS-Tailwind/tsconfig.node.json
  public/TodoList-React-TS-Tailwind/vite.config.ts
Labels: enhancement, ADVANCE, SWOC, points-assignment-done

#575 added Time Capsule Project
  index.js
  public/Time-Capsule/index.html
  public/Time-Capsule/script.js
  public/Time-Capsule/style.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#581 Chnages to the TO-DO list
  public/TO_DO_LIST/todolist.css
  public/TO_DO_LIST/todolist.html
  public/TO_DO_LIST/todolist.js
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#587 Improved Content and the shadow effect of text
  parallal.css
  parallal.html
Labels: enhancement, BEGINNER, SWOC, points-assignment-done

#583 Virtual piano project
  index.js
  public/Virtual Piano/PianoNotes/key08.mp3
  public/Virtual Piano/PianoNotes/key09.mp3
  public/Virtual Piano/PianoNotes/key10.mp3
  public/Virtual Piano/PianoNotes/key11.mp3
  public/Virtual Piano/PianoNotes/key12.mp3
  public/Virtual Piano/PianoNotes/key13.mp3
  public/Virtual Piano/PianoNotes/key14.mp3
  public/Virtual Piano/PianoNotes/key15.mp3
  public/Virtual Piano/PianoNotes/key16.mp3
  public/Virtual Piano/PianoNotes/key17.mp3
  public/Virtual Piano/PianoNotes/key18.mp3
  public/Virtual Piano/PianoNotes/key19.mp3
  public/Virtual Piano/PianoNotes/key20.mp3
  public/Virtual Piano/PianoNotes/key21.mp3
  public/Virtual Piano/PianoNotes/key22.mp3
  public/Virtual Piano/PianoNotes/key23.mp3
  public/Virtual Piano/PianoNotes/key24.mp3
  public/Virtual Piano/index.html
  public/Virtual Piano/index.js
  public/Virtual Piano/style.css
Labels: enhancement, ADVANCE, SWOC, points-assignment-done

#573 Added NASA_APOD - Browser Extension
  index.js
  public/NASA-APOD/background.js
  public/NASA-APOD/icon128.png
  public/NASA-APOD/icon16.png
  public/NASA-APOD/icon48.png
  public/NASA-APOD/manifest.json
  public/NASA-APOD/popup.css
  public/NASA-APOD/popup.html
  public/NASA-APOD/popup.js
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#576 Adding Text Saver Extension
  index.js
  public/Text_Saver_Ext/README.md
  public/Text_Saver_Ext/background.js
  public/Text_Saver_Ext/content.js
  public/Text_Saver_Ext/manifest.json
  public/Text_Saver_Ext/popup.html
  public/Text_Saver_Ext/popup.js
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#582 Finance tracker
  index.js
  public/FinanceTracker/index.html
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#550 Added travel booking website
  index.js
  public/Travel_booking_website/App_Store_.png
  public/Travel_booking_website/air.jpg
  public/Travel_booking_website/car1.jpg
  public/Travel_booking_website/cilent3.jpg
  public/Travel_booking_website/city1.jpg
  public/Travel_booking_website/city2.jpg
  public/Travel_booking_website/client1.jpg
  public/Travel_booking_website/client2.jpg
  public/Travel_booking_website/client4.jpg
  public/Travel_booking_website/client5.jpg
  public/Travel_booking_website/dubai.jpg
  public/Travel_booking_website/dubainight.jpg
  public/Travel_booking_website/flight book.jpg
  public/Travel_booking_website/fly travel logo.jpg
  public/Travel_booking_website/flyapplogo.png
  public/Travel_booking_website/google play.jpg
  public/Travel_booking_website/hotel1.jpg
  public/Travel_booking_website/hotel2.jpg
  public/Travel_booking_website/index.html
  public/Travel_booking_website/index.js
  public/Travel_booking_website/maldives.jpg
  public/Travel_booking_website/service1.jpg
  public/Travel_booking_website/service2.jpg
  public/Travel_booking_website/service3.jpg
  public/Travel_booking_website/sip1.jpg
  public/Travel_booking_website/style.css
  public/pig_game/dice-1.png
  public/pig_game/dice-2.png
  public/pig_game/dice-3.png
  public/pig_game/dice-4.png
  public/pig_game/dice-5.png
  public/pig_game/dice-6.png
  public/pig_game/ex.html
  public/pig_game/firecrackers.html
  public/pig_game/index.html
  public/pig_game/index.js
  public/pig_game/style.css
Labels: ADVANCE, SWOC, points-assignment-done

#577 Added Drumkit Game
  index.js
  public/Drumkit_Game/.idea/.gitignore
  public/Drumkit_Game/.idea/DrumKit.iml
  public/Drumkit_Game/.idea/modules.xml
  public/Drumkit_Game/.idea/vcs.xml
  public/Drumkit_Game/README.md
  public/Drumkit_Game/images/17973908.jpg
  public/Drumkit_Game/images/crash.png
  public/Drumkit_Game/images/kick.png
  public/Drumkit_Game/images/snare.png
  public/Drumkit_Game/images/tom1.png
  public/Drumkit_Game/images/tom2.png
  public/Drumkit_Game/images/tom3.png
  public/Drumkit_Game/images/tom4.png
  public/Drumkit_Game/index.html
  public/Drumkit_Game/index.js
  public/Drumkit_Game/sounds/crash.mp3
  public/Drumkit_Game/sounds/kick-bass.mp3
  public/Drumkit_Game/sounds/snare.mp3
  public/Drumkit_Game/sounds/tom-1.mp3
  public/Drumkit_Game/sounds/tom-2.mp3
  public/Drumkit_Game/sounds/tom-3.mp3
  public/Drumkit_Game/sounds/tom-4.mp3
  public/Drumkit_Game/styles.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#590 Updated Day 90 Quize App Timer
  index.js
  public/QuizeApp Timer/app.css
  public/QuizeApp Timer/index1.html
  public/QuizeApp Timer/script.js
  public/knowledge quiz/app.css
  public/knowledge quiz/index1.html
  public/knowledge quiz/script.js
Labels: INTERMEDIATE, SWOC, points-assignment-done

#594 Theme selection in digital clock
  theme selection
Labels: enhancement, BEGINNER, SWOC, points-assignment-done

#598 Add hover effects and Log-In page design
  Imagemain.png
  forgot-password.html
  index.css
  index.html
  public/Login.html
  public/login.css
  public/signup.html
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#601 Day 104 Periodic Table Fixed
  index.js
  public/Periodic Table/index.html
  public/Periodic Table/script.js
  public/Periodic Table/styles.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#604 Updated the UI to add animations to it+Backend
  public/Love-Calculator/index.html
  public/Love-Calculator/pink-realistic-heart-isolate-on-transparente-background-symbol-love-3d-heart-icon-png.webp
  public/Love-Calculator/script.js
  public/Love-Calculator/style.css
  public/Love-Calculator/white-3d-heart-free-png.webp
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#609 [Readme.md Updation] Created Table for all Projects Listings in README.md file
  README.md
Labels: documentation, BEGINNER, SWOC, points-assignment-done

#610 Added New Frontend Project Plants Website
  index.js
  public/Plants Website/images/about.png
  public/Plants Website/images/contact.jpg
  public/Plants Website/images/faq.png
  public/Plants Website/images/home.jpg
  public/Plants Website/images/img-1.jpg
  public/Plants Website/images/img-2.jpg
  public/Plants Website/images/img-3.jpg
  public/Plants Website/images/img-4.jpg
  public/Plants Website/images/plant-1.png
  public/Plants Website/images/plant-2.png
  public/Plants Website/images/plant-3.png
  public/Plants Website/index.html
  public/Plants Website/script.js
  public/Plants Website/style.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#611 Adding a New Project called Expense Tracker
  public/DocNow/docstyle.css
  public/DocNow/images/AndroidPNG.png
  public/DocNow/images/ability_img.png
  public/DocNow/images/app.png
  public/DocNow/images/banner_1.svg
  public/DocNow/images/banner_img.jpg
  public/DocNow/images/docnow.png
  public/DocNow/images/iosPNG.png
  public/DocNow/images/next.png
  public/DocNow/index.html
  public/DocNow/pages/about.html
  public/DocNow/pages/appointment.html
  public/DocNow/pages/contact.html
  public/DocNow/pages/doctors.html
  public/DocNow/pages/services.html
  public/expense_Tracker/index.html
  public/expense_Tracker/style.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#615 Add Mood Tracker App
  index.js
  public/Mood Tracker/index.html
  public/Mood Tracker/script.js
  public/Mood Tracker/styles.css
Labels: enhancement, BEGINNER, SWOC, points-assignment-done

#623 ADDING CRYPTOSHOW
  index.js
  public/CRYPTOSHOW/.eslintrc.cjs
  public/CRYPTOSHOW/.gitignore
  public/CRYPTOSHOW/README.md
  public/CRYPTOSHOW/index.html
  public/CRYPTOSHOW/package-lock.json
  public/CRYPTOSHOW/package.json
  public/CRYPTOSHOW/public/vite.svg
  public/CRYPTOSHOW/src/App.jsx
  public/CRYPTOSHOW/src/assets/arrow_icon.png
  public/CRYPTOSHOW/src/assets/favicon-32x32.png
  public/CRYPTOSHOW/src/assets/logo.png
  public/CRYPTOSHOW/src/assets/react.svg
  public/CRYPTOSHOW/src/components/Footer/Footer.css
  public/CRYPTOSHOW/src/components/Footer/Footer.jsx
  public/CRYPTOSHOW/src/components/LineChart/LineChart.css
  public/CRYPTOSHOW/src/components/LineChart/LineChart.jsx
  public/CRYPTOSHOW/src/components/Navbar/Navbar.css
  public/CRYPTOSHOW/src/components/Navbar/Navbar.jsx
  public/CRYPTOSHOW/src/context/CoinContext.jsx
  public/CRYPTOSHOW/src/index.css
  public/CRYPTOSHOW/src/main.jsx
  public/CRYPTOSHOW/src/pages/Coin/Coin.css
  public/CRYPTOSHOW/src/pages/Coin/Coin.jsx
  public/CRYPTOSHOW/src/pages/Home/Home.css
  public/CRYPTOSHOW/src/pages/Home/Home.jsx
  public/CRYPTOSHOW/src/pages/converter/Converter.css
  public/CRYPTOSHOW/src/pages/converter/Converter.jsx
  public/CRYPTOSHOW/src/pages/news/News.css
  public/CRYPTOSHOW/src/pages/news/Newses.jsx
  public/CRYPTOSHOW/vite.config.js
Labels: INTERMEDIATE, SWOC, points-assignment-done

#624 Image update
  public/Netflix_Cloning/Index.html
  public/TO_DO_LIST/todolist.js
  public/carousal/images/Neptune.png
  public/carousal/images/Uranus.png
  public/carousal/images/uranus-image.png
  public/carousal/index.css
  public/carousal/index.html
  public/carousal/index.js
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#637 add navbar to login ,sign up and forgot password page
  forgot-password.html
  public/Login.html
  public/login.css
  public/signup.html
Labels: enhancement, BEGINNER, SWOC, points-assignment-done

#627 Update style.css
  public/MemoryGame/style.css
Labels: BEGINNER, SWOC, points-assignment-done

#628 Add Calculator Project
  public/Calculator/Calculator.css
  public/Calculator/Calculator.html
  public/Calculator/Calculator.js
Labels: BEGINNER, SWOC, points-assignment-done

#643 Spotify clone new
  public/spotify clone/cover.jpg
  public/spotify clone/image/A.R. Rahman.png
  public/spotify clone/image/All Out 80s.jpg
  public/spotify clone/image/Arijit Singh.png
  public/spotify clone/image/Beats to think to.jpg
  public/spotify clone/image/Deep Focus.jpg
  public/spotify clone/image/Focus Flow.jpg
  public/spotify clone/image/Instrumental Study.jpg
  public/spotify clone/image/Peaceful Piano.jpg
  public/spotify clone/image/Pritam.png
  public/spotify clone/image/Reading Adventure.jpg
  public/spotify clone/image/Sachin-Jigar.png
  public/spotify clone/image/Spotify Logo.png
  public/spotify clone/image/Spotify_favicon.png
  public/spotify clone/image/The Sound of Bengaluru.jpg
  public/spotify clone/image/The Sound of Chennai.jpg
  public/spotify clone/image/The Sound of Delhi.jpg
  public/spotify clone/image/The Sound of Hyderabad.jpg
  public/spotify clone/image/The Sound of Kolkata.jpg
  public/spotify clone/image/The Sound of Mumbai.jpg
  public/spotify clone/image/Today_s Top Hits.jpg
  public/spotify clone/image/Vishal-Shekhar.png
  public/spotify clone/image/Workday Lounge.jpg
  public/spotify clone/image/logo.png
  public/spotify clone/index.html
  public/spotify clone/login.html
  public/spotify clone/styles.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#645 Plant simulation(New Project)
  public/Plant/images/R.png
  public/Plant/images/back.webp
  public/Plant/images/flowering.png
  public/Plant/images/sap3.webp
  public/Plant/images/sapling2.png
  public/Plant/images/seeds.webp
  public/Plant/images/stage-2-veretation.png
  public/Plant/main.html
  public/Plant/script.js
  public/Plant/style.css
Labels: BEGINNER, SWOC, points-assignment-done

#655 Jokes site
  public/jokes_site/3-32410_clip-art-library-kids-free-for-download-laughing.png
  public/jokes_site/index.html
  public/jokes_site/script.js
  public/jokes_site/style.css
Labels: INTERMEDIATE, SWOC, points-assignment-done

#687 Music Bandzzzz(New Website)
  public/music_website/back.jpg
  public/music_website/download.jpeg
  public/music_website/index.html
  public/music_website/style.css
Labels: INTERMEDIATE, SWOC, points-assignment-done

#675 Enhance Contributors Page
  contributors/contributor.css
  contributors/contributor.html
  index.html
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#684 [README.md] Added Day 79 to Day 110 + folder locations
  README.md
Labels: documentation, enhancement, BEGINNER, SWOC, points-assignment-done

#682 Personal Website
  public/Personal_website/index.html
  public/Personal_website/style.css
  public/Personal_website/team-1-640x640.jpg
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#672 Highly NEEDED: Improved Site UI
  index.css
  index.html
  index.js
Labels: enhancement, ADVANCE, SWOC, points-assignment-done
