Repository dhairyagothi/100_days_100_web_project, pull requests merged in 2025-02, with the labels that each got.

#697 Added Nykaa-Clone Website + Corrected The CSS
  index.css
  index.js
  public/Nykaa-clone/hardtoResistDeals.js
  public/Nykaa-clone/index.html
  public/Nykaa-clone/listofProduct.js
  public/Nykaa-clone/public/logo.png
  public/Nykaa-clone/public/logo.svg
  public/Nykaa-clone/script.js
  public/Nykaa-clone/style.css
  public/Nykaa-clone/topbrands.js
Labels: enhancement, ADVANCE, SWOC, points-assignment-done

#694 Changes1
  public/color_picker/index.html
  public/color_picker/script.js
  public/color_picker/style.css
  public/music_website/OIP (1).jpeg
  public/music_website/main.html
  public/music_website/maxresdefault.jpg
  public/music_website/pages/events.css
  public/music_website/pages/events.html
Labels: enhancement, good first issue, INTERMEDIATE, SWOC, points-assignment-done

#721 Generate Certificates for Contributors
  contributors/contributor.css
  contributors/contributor.js
Labels: enhancement, ADVANCE, SWOC, points-assignment-done

#703 Add login
  public/spotify-clone -project/index.html
  public/spotify-clone -project/styles.css
Labels: enhancement, BEGINNER, SWOC, points-assignment-done

#695 GameQuest (New Project)
  blog.html
  girl.png.png
  index.html
  script.js
  style.css
Labels: enhancement, ADVANCE, SWOC, points-assignment-done

#634 Fix: Resolved currency conversion issue
  public/Exchange_Currency/app.js
  public/Exchange_Currency/index.html
  public/Exchange_Currency/style.css
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done

#673 Fix, Skills option describes the work in Resume Studio
  public/ResumeStudio/script.js
Labels: BEGINNER, SWOC, points-assignment-done

#658 Enhanced the visibility of nav bar
  public/Parallel-x website/parallal.css
Labels: BEGINNER, SWOC, points-assignment-done

#732 Recipe Selector Web App
  public/Holo Button/circle.png
  public/Holo Button/index.html
  public/Holo Button/style.css
  public/Stone-Paper-Scissor/index.html
  public/Stone-Paper-Scissor/script.js
  public/Stone-Paper-Scissor/style.css
  public/Stone-Paper-Scissor/style1.css
  public/recipe/image.jpg
  public/recipe/main.html
  public/recipe/rec.html
  public/recipe/style.css
  public/recipe/text.json
Labels: enhancement, INTERMEDIATE, SWOC, points-assignment-done
